Abilities:
  EarthQuake:
    Enabled: true
    Cooldown: 8000
    Duration: 5000
    Radius: 5.5
    DamageInterval: 650
    Damage: 1.0
    Slowness:
      Enabled: true
      Potency: 1
    RemovalPolicy:
      RequireSneak: true
      AllowDifferentSlots: false
      UserMustBeInRadius: true
      EnforceGroundDirection: true
      MaxPitchDifference: 45.0
  RockBullets:
    Enabled: true
    Cooldown: 12000
    Duration: 3000
    Interval: 333
    Damage: 1.0
    Range: 15
    RemovalPolicy:
      AllowDifferentSlots: false
  CrustShatter:
    Enabled: true
    Cooldown: 14000
    Charge: 250
    Damage: 3
    Range: 8
    FallingBlocks: true
    ArrowVisual: true
    WidthIncrement: 0.25
  RockLike:
    Enabled: true
  EarthSlide:
    Enabled: true
    Speed: 0.6
Strings:
  EarthQuake:
    Description: 'EarthQuake lets the user shake the earth beneath them in a set radius, damaging the entities inside.'
    Instructions: 'Left click on a block while sneaking.'
  RockBullets:
    Description: 'Allows the user to fire rocks rapidly towards entities, dealing damage.'
    Instructions: 'Left click while sneaking, requires an earthbendable towards the right side of the player.'
  CrustShatter:
    Description: 'This ability allows the user to smash the ground, shaking it and damaging the enemies in front inside a cone shape.'
    Instructions: 'EarthQuake (Hold sneak) > Shockwave (Left click) > Shockwave (Release sneak) > EarthSmash (Tap sneak)'
  RockLike:
    Description: 'This passive makes the user is immune to knockback caused by other attackers if theyre sneaking.'
  EarthSlide:
    Description: 'This passive lets the user slide while using EarthArmor'