Abilities:
  EarthQuake:
    Enabled: true
    Cooldown: 8000
    Duration: 5000
    Radius: 3.5
    DamageInterval: 650
    Damage: 1.0
    Slowness:
      Enabled: true
      Potency: 1
    RemovalPolicy:
      RequireSneak: true
      AllowDifferentSlots: false
      UserMustBeInRadius: true
      EnforceGroundDirection: true
      MaximumPitchDifference: 45.0
  RockBullets:
    Enabled: true
    Cooldown: 12000
    Duration: 3000
    Interval: 333
    Damage: 1.0
Strings:
  EarthQuake:
    Description: 'EarthQuake lets the user shake the earth beneath them in a set radius, damaging the entities inside.'
    Instructions: 'Right click on a block while sneaking.'
  RockBullets:
    Description: ''
    Instructions: ''