Abilities:
  EarthQuake:
    Enabled: true
    Cooldown: 8000
    Duration: 5000
    Radius: 5.5
    DamageInterval: 650
    Damage: 1.0
    Slowness:
      Enabled: true
      Potency: 1
    RemovalPolicy:
      RequireSneak: true
      AllowDifferentSlots: false
      UserMustBeInRadius: true
      EnforceGroundDirection: true
      MaxPitchDifference: 45.0
  RockBullets:
    Enabled: true
    Cooldown: 12000
    Duration: 3000
    Interval: 333
    Damage: 1.0
    Range: 15
    RemovalPolicy:
      AllowDifferentSlots: false
  RockLike:
    Enabled: true
Strings:
  EarthQuake:
    Description: 'EarthQuake lets the user shake the earth beneath them in a set radius, damaging the entities inside.'
    Instructions: 'Left click on a block while sneaking.'
  RockBullets:
    Description: 'Allows the user to fire rocks rapidly towards entities, dealing damage.'
    Instructions: 'Left click while sneaking, requires an earthbendable towards the right side of the player.'
  RockLike:
    Description: 'This passive makes the user is immune to knockback caused by other attackers if theyre sneaking.'
